### PR TITLE
add an optional selectEventName function

### PR DESCRIPTION
**Pull request by tomru**
…on types to mixpanel events

### CODE REVIEW

**Comment by kamilio** [comment]
Typo - optional

**Comment by tomru** [comment]
doh

**Comment by kamilio** [comment]
With this function you can translate the stuff, or select something else to use as eventName instead of type. 

I think it could use an example in readme.

**Comment by thatguynamedandy** [comment]
Agree with @kamilio on an example.

**Comment by tomru** [comment]
good point, added an example to the readme now.

**Pull request merged**
